---
- name: Deploy OVA Template
  vmware_deploy_ovf:
    hostname: "{{ ova_deployment_hostname }}"
    username: "{{ ova_deployment_username }}"
    password: "{{ ova_deployment_password }}"
    validate_certs: "{{ ova_validate_certs }}"
    ova: "{{ ova_path }}/{{ ova_file }}"
    name: "{{ inventory_hostname_short | upper }}"
    folder: "{{ ova_deployment_folder | default(omit) }}"
    datacenter: "{{ ova_deployment_datacenter | default(omit) }}"
    cluster: "{{ ova_deployment_cluster | default(omit) }}"
    resource_pool: "{{ ova_deployment_resource_pool | default(omit) }}"
    datastore: "{{ ova_deployment_datastore }}"
    disk_provisioning: "{{ ova_deployment_disk_type }}"
    networks: "{{ ova_networks }}"
    allow_duplicates: "{{ ova_allow_duplicates }}"
    power_on: no
    deployment_option: "{{ ova_deployment_option | default(omit) }}"
    fail_on_spec_warnings: yes
    wait: no
    wait_for_ip_address: no
    properties: "{{ ova_properties }}"
    inject_ovf_env: yes
  delegate_to: localhost
  register: ova_imported
