---
- include_tasks: check_file_exists.yml

- include_tasks: download_ova_file.yml
  when: |
    ova_source|lower == "http" and
    not (check_ova_file.stat.exists|bool)

- include_tasks: import_ova_template.yml
  when: |
    check_ova_file.stat.exists|bool or
    ova_file_download.changed|bool

- include_tasks: set_vapp_properties.yml
  when: |
    vapp_properties is defined and
    ova_imported.changed|bool

- name: Configure Virtual Machine Hardware
  include_tasks: configure_hardware.yml
  when: |
    
- include_tasks: power_on_ova.yml
  when: ova_power_on_after_deploy|bool